### ISSUE TITLE
MiniWinFile_Common/window_file.c:380: undefined reference

### ISSUE THREAD

**Issue by StuartRothrock** [miniwinwm/miniwinwm#2]
Looks like a header file reference may be missing:
/miniwinwm/RaspberryPi/ZeroW/MiniWinFile/../../../MiniWinFile_Common/window_file.c:380: undefined reference to `mw_create_window_dialog_file_chooser'

**Comment by miniwinwm** [comment]
I'll check this out and test it but in the meantime try this solution...

Because the way the makefiles use wildcards this issue can arise when you move from one project to another without doing a make clean in between.

**Comment by miniwinwm** [comment]
Confirmation. I can reproduce it by building MiniWinSimple then MiniWinFile without doing a make clean in between for RPi Zero variant. This has been seen before & is mentioned somewhere deep in the manual.

Workaround: Do a make clean when moving between projects. This applies to all makefile built projects on all hardware variants. The Linux Eclipse IDE built projects simply call the makefiles externally, so it applies to them as well. The ST, NXP, RX & PIC32 example projects are unaffected.

Solution: In the meantime add a small readme file in the root folder of affected projects as they get read over the manual. Wildcards need replacing in makefiles with something better. This is for the future as an easy workaround exists.

**Comment by StuartRothrock** [comment]
Thanks - the make clean resolved my issue - live and learn - thanks again
